export {default as Dashboard} from "./dashboard/dashboard"
export {default as Login} from "./login/login"
export {default as Post} from "./post/post"
export {default as Posts} from "./posts/posts"
export {default as NewPost} from "./newPost/newPost"
export {default as Profile} from "./profil/profile"
export {default as StatisticPage} from "./statistic/statistic"
export {default as CardItem } from "./dashboard/Card/CardItem"
export {default as Video } from "./video/video"
export {default as Message} from "./message/message"
export {default as NewCategory} from "./newCategory/newCategory"
export {default as ShortNews} from "./shortNews/shortNews"
export {default as AllFiles} from "./AllFiles/AllFiles"